# Generated by Django 3.1.1 on 2020-09-09 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 9, 8, 28, 32, 281473, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
