# Generated by Django 3.1.1 on 2020-09-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
